# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sts_realm_swift_notebook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sts_realm_swift_notebook
	pod ‘RealmSwift’

  target 'sts_realm_swift_notebookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sts_realm_swift_notebookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
